data = [
    "Accordion",
    "Affix",
    "Alert",
    "Badge",
    "Button",
    # "Checkbox",
    # "Chips",
    # "DatePicker",
    # "DateRangePicker",
    # "Divider",
    # "Drawer",
    # "Image",
    # "Modal",
    # "MultiSelect",
    # "Notifications",
    # "Paper",
    # "Prism",
    # "Progress",
    # "RadioGroup",
    # "SegmentedControl",
    # "Select",
    # "Slider",
    # "Spoiler",
    # "Switch",
    # "Table",
    # "Tabs",
    # "Text",
    # "TextInput",
    # "Title",
    # "Tooltip",
]
