import dash_mantine_components as dmc

dark_color_scheme =  [
    {"--mantine-primary-color-contrast": "var(--mantine-color-white)"},
    {"--mantine-color-bright": "var(--mantine-color-white)"},
    {"--mantine-color-text": "var(--mantine-color-dark-0)"},
    {"--mantine-color-body": "var(--mantine-color-dark-7)"},
    {"--mantine-color-error": "var(--mantine-color-red-8)"},
    {"--mantine-color-placeholder": "var(--mantine-color-dark-3)"},
    {"--mantine-color-anchor": "var(--mantine-color-blue-4)"},
    {"--mantine-color-default": "var(--mantine-color-dark-6)"},
    {"--mantine-color-default-hover": "var(--mantine-color-dark-5)"},
    {"--mantine-color-default-color": "var(--mantine-color-white)"},
    {"--mantine-color-default-border": "var(--mantine-color-dark-4)"},
    {"--mantine-color-dimmed": "var(--mantine-color-dark-2)"},
    {"--mantine-color-dark-text": "var(--mantine-color-dark-4)"},
    {"--mantine-color-dark-filled": "var(--mantine-color-dark-8)"},
    {"--mantine-color-dark-filled-hover": "var(--mantine-color-dark-9)"},
    {"--mantine-color-dark-light": "rgba(46, 46, 46, 0.15)"},
    {"--mantine-color-dark-light-hover": "rgba(46, 46, 46, 0.2)"},
    {"--mantine-color-dark-light-color": "var(--mantine-color-dark-3)"},
    {"--mantine-color-dark-outline": "var(--mantine-color-dark-4)"},
    {"--mantine-color-dark-outline-hover": "rgba(66, 66, 66, 0.05)"},
    {"--mantine-color-gray-text": "var(--mantine-color-gray-4)"},
    {"--mantine-color-gray-filled": "var(--mantine-color-gray-8)"},
    {"--mantine-color-gray-filled-hover": "var(--mantine-color-gray-9)"},
    {"--mantine-color-gray-light": "rgba(134, 142, 150, 0.15)"},
    {"--mantine-color-gray-light-hover": "rgba(134, 142, 150, 0.2)"},
    {"--mantine-color-gray-light-color": "var(--mantine-color-gray-3)"},
    {"--mantine-color-gray-outline": "var(--mantine-color-gray-4)"},
    {"--mantine-color-gray-outline-hover": "rgba(206, 212, 218, 0.05)"},
    {"--mantine-color-red-text": "var(--mantine-color-red-4)"},
    {"--mantine-color-red-filled": "var(--mantine-color-red-8)"},
    {"--mantine-color-red-filled-hover": "var(--mantine-color-red-9)"},
    {"--mantine-color-red-light": "rgba(250, 82, 82, 0.15)"},
    {"--mantine-color-red-light-hover": "rgba(250, 82, 82, 0.2)"},
    {"--mantine-color-red-light-color": "var(--mantine-color-red-3)"},
    {"--mantine-color-red-outline": "var(--mantine-color-red-4)"},
    {"--mantine-color-red-outline-hover": "rgba(255, 135, 135, 0.05)"},
    {"--mantine-color-pink-text": "var(--mantine-color-pink-4)"},
    {"--mantine-color-pink-filled": "var(--mantine-color-pink-8)"},
    {"--mantine-color-pink-filled-hover": "var(--mantine-color-pink-9)"},
    {"--mantine-color-pink-light": "rgba(230, 73, 128, 0.15)"},
    {"--mantine-color-pink-light-hover": "rgba(230, 73, 128, 0.2)"},
    {"--mantine-color-pink-light-color": "var(--mantine-color-pink-3)"},
    {"--mantine-color-pink-outline": "var(--mantine-color-pink-4)"},
    {"--mantine-color-pink-outline-hover": "rgba(247, 131, 172, 0.05)"},
    {"--mantine-color-grape-text": "var(--mantine-color-grape-4)"},
    {"--mantine-color-grape-filled": "var(--mantine-color-grape-8)"},
    {"--mantine-color-grape-filled-hover": "var(--mantine-color-grape-9)"},
    {"--mantine-color-grape-light": "rgba(190, 75, 219, 0.15)"},
    {"--mantine-color-grape-light-hover": "rgba(190, 75, 219, 0.2)"},
    {"--mantine-color-grape-light-color": "var(--mantine-color-grape-3)"},
    {"--mantine-color-grape-outline": "var(--mantine-color-grape-4)"},
    {"--mantine-color-grape-outline-hover": "rgba(218, 119, 242, 0.05)"},
    {"--mantine-color-violet-text": "var(--mantine-color-violet-4)"},
    {"--mantine-color-violet-filled": "var(--mantine-color-violet-8)"},
    {"--mantine-color-violet-filled-hover": "var(--mantine-color-violet-9)"},
    {"--mantine-color-violet-light": "rgba(121, 80, 242, 0.15)"},
    {"--mantine-color-violet-light-hover": "rgba(121, 80, 242, 0.2)"},
    {"--mantine-color-violet-light-color": "var(--mantine-color-violet-3)"},
    {"--mantine-color-violet-outline": "var(--mantine-color-violet-4)"},
    {"--mantine-color-violet-outline-hover": "rgba(151, 117, 250, 0.05)"},
    {"--mantine-color-indigo-text": "var(--mantine-color-indigo-4)"},
    {"--mantine-color-indigo-filled": "var(--mantine-color-indigo-8)"},
    {"--mantine-color-indigo-filled-hover": "var(--mantine-color-indigo-9)"},
    {"--mantine-color-indigo-light": "rgba(76, 110, 245, 0.15)"},
    {"--mantine-color-indigo-light-hover": "rgba(76, 110, 245, 0.2)"},
    {"--mantine-color-indigo-light-color": "var(--mantine-color-indigo-3)"},
    {"--mantine-color-indigo-outline": "var(--mantine-color-indigo-4)"},
    {"--mantine-color-indigo-outline-hover": "rgba(116, 143, 252, 0.05)"},
    {"--mantine-color-blue-text": "var(--mantine-color-blue-4)"},
    {"--mantine-color-blue-filled": "var(--mantine-color-blue-8)"},
    {"--mantine-color-blue-filled-hover": "var(--mantine-color-blue-9)"},
    {"--mantine-color-blue-light": "rgba(34, 139, 230, 0.15)"},
    {"--mantine-color-blue-light-hover": "rgba(34, 139, 230, 0.2)"},
    {"--mantine-color-blue-light-color": "var(--mantine-color-blue-3)"},
    {"--mantine-color-blue-outline": "var(--mantine-color-blue-4)"},
    {"--mantine-color-blue-outline-hover": "rgba(77, 171, 247, 0.05)"},
    {"--mantine-color-cyan-text": "var(--mantine-color-cyan-4)"},
    {"--mantine-color-cyan-filled": "var(--mantine-color-cyan-8)"},
    {"--mantine-color-cyan-filled-hover": "var(--mantine-color-cyan-9)"},
    {"--mantine-color-cyan-light": "rgba(21, 170, 191, 0.15)"},
    {"--mantine-color-cyan-light-hover": "rgba(21, 170, 191, 0.2)"},
    {"--mantine-color-cyan-light-color": "var(--mantine-color-cyan-3)"},
    {"--mantine-color-cyan-outline": "var(--mantine-color-cyan-4)"},
    {"--mantine-color-cyan-outline-hover": "rgba(59, 201, 219, 0.05)"},
    {"--mantine-color-teal-text": "var(--mantine-color-teal-4)"},
    {"--mantine-color-teal-filled": "var(--mantine-color-teal-8)"},
    {"--mantine-color-teal-filled-hover": "var(--mantine-color-teal-9)"},
    {"--mantine-color-teal-light": "rgba(18, 184, 134, 0.15)"},
    {"--mantine-color-teal-light-hover": "rgba(18, 184, 134, 0.2)"},
    {"--mantine-color-teal-light-color": "var(--mantine-color-teal-3)"},
    {"--mantine-color-teal-outline": "var(--mantine-color-teal-4)"},
    {"--mantine-color-teal-outline-hover": "rgba(56, 217, 169, 0.05)"},
    {"--mantine-color-green-text": "var(--mantine-color-green-4)"},
    {"--mantine-color-green-filled": "var(--mantine-color-green-8)"},
    {"--mantine-color-green-filled-hover": "var(--mantine-color-green-9)"},
    {"--mantine-color-green-light": "rgba(64, 192, 87, 0.15)"},
    {"--mantine-color-green-light-hover": "rgba(64, 192, 87, 0.2)"},
    {"--mantine-color-green-light-color": "var(--mantine-color-green-3)"},
    {"--mantine-color-green-outline": "var(--mantine-color-green-4)"},
    {"--mantine-color-green-outline-hover": "rgba(105, 219, 124, 0.05)"},
    {"--mantine-color-lime-text": "var(--mantine-color-lime-4)"},
    {"--mantine-color-lime-filled": "var(--mantine-color-lime-8)"},
    {"--mantine-color-lime-filled-hover": "var(--mantine-color-lime-9)"},
    {"--mantine-color-lime-light": "rgba(130, 201, 30, 0.15)"},
    {"--mantine-color-lime-light-hover": "rgba(130, 201, 30, 0.2)"},
    {"--mantine-color-lime-light-color": "var(--mantine-color-lime-3)"},
    {"--mantine-color-lime-outline": "var(--mantine-color-lime-4)"},
    {"--mantine-color-lime-outline-hover": "rgba(169, 227, 75, 0.05)"},
    {"--mantine-color-yellow-text": "var(--mantine-color-yellow-4)"},
    {"--mantine-color-yellow-filled": "var(--mantine-color-yellow-8)"},
    {"--mantine-color-yellow-filled-hover": "var(--mantine-color-yellow-9)"},
    {"--mantine-color-yellow-light": "rgba(250, 176, 5, 0.15)"},
    {"--mantine-color-yellow-light-hover": "rgba(250, 176, 5, 0.2)"},
    {"--mantine-color-yellow-light-color": "var(--mantine-color-yellow-3)"},
    {"--mantine-color-yellow-outline": "var(--mantine-color-yellow-4)"},
    {"--mantine-color-yellow-outline-hover": "rgba(255, 212, 59, 0.05)"},
    {"--mantine-color-orange-text": "var(--mantine-color-orange-4)"},
    {"--mantine-color-orange-filled": "var(--mantine-color-orange-8)"},
    {"--mantine-color-orange-filled-hover": "var(--mantine-color-orange-9)"},
    {"--mantine-color-orange-light": "rgba(253, 126, 20, 0.15)"},
    {"--mantine-color-orange-light-hover": "rgba(253, 126, 20, 0.2)"},
    {"--mantine-color-orange-light-color": "var(--mantine-color-orange-3)"},
    {"--mantine-color-orange-outline": "var(--mantine-color-orange-4)"},
    {"--mantine-color-orange-outline-hover": "rgba(255, 169, 77, 0.05)"}
]

def make_rows(data):
    rows = [
        dmc.Grid([
            dmc.GridCol(dmc.Text(key), span=5),
            dmc.GridCol(dmc.Text(value), span=5),
            dmc.GridCol(dmc.Box(h=24, w=24, bg=value), span=2),
            dmc.GridCol(dmc.Divider(), span=12)
        ])
        for item in data
        for key, value in item.items()
    ]
    return rows


component =  dmc.Box(
    make_rows(dark_color_scheme)
)


