import dash_mantine_components as dmc


light_color_scheme = [
    {"--mantine-primary-color-contrast": "var(--mantine-color-white)"},
    {"--mantine-color-bright": "var(--mantine-color-black)"},
    {"--mantine-color-text": "#000"},
    {"--mantine-color-body": "#fff"},
    {"--mantine-color-error": "var(--mantine-color-red-6)"},
    {"--mantine-color-placeholder": "var(--mantine-color-gray-5)"},
    {"--mantine-color-anchor": "var(--mantine-color-blue-6)"},
    {"--mantine-color-default": "var(--mantine-color-white)"},
    {"--mantine-color-default-hover": "var(--mantine-color-gray-0)"},
    {"--mantine-color-default-color": "var(--mantine-color-black)"},
    {"--mantine-color-default-border": "var(--mantine-color-gray-4)"},
    {"--mantine-color-dimmed": "var(--mantine-color-gray-6)"},
    {"--mantine-color-dark-text": "var(--mantine-color-dark-filled)"},
    {"--mantine-color-dark-filled": "var(--mantine-color-dark-6)"},
    {"--mantine-color-dark-filled-hover": "var(--mantine-color-dark-7)"},
    {"--mantine-color-dark-light": "rgba(46, 46, 46, 0.1)"},
    {"--mantine-color-dark-light-hover": "rgba(46, 46, 46, 0.12)"},
    {"--mantine-color-dark-light-color": "var(--mantine-color-dark-6)"},
    {"--mantine-color-dark-outline": "var(--mantine-color-dark-6)"},
    {"--mantine-color-dark-outline-hover": "rgba(46, 46, 46, 0.05)"},
    {"--mantine-color-gray-text": "var(--mantine-color-gray-filled)"},
    {"--mantine-color-gray-filled": "var(--mantine-color-gray-6)"},
    {"--mantine-color-gray-filled-hover": "var(--mantine-color-gray-7)"},
    {"--mantine-color-gray-light": "rgba(134, 142, 150, 0.1)"},
    {"--mantine-color-gray-light-hover": "rgba(134, 142, 150, 0.12)"},
    {"--mantine-color-gray-light-color": "var(--mantine-color-gray-6)"},
    {"--mantine-color-gray-outline": "var(--mantine-color-gray-6)"},
    {"--mantine-color-gray-outline-hover": "rgba(134, 142, 150, 0.05)"},
    {"--mantine-color-red-text": "var(--mantine-color-red-filled)"},
    {"--mantine-color-red-filled": "var(--mantine-color-red-6)"},
    {"--mantine-color-red-filled-hover": "var(--mantine-color-red-7)"},
    {"--mantine-color-red-light": "rgba(250, 82, 82, 0.1)"},
    {"--mantine-color-red-light-hover": "rgba(250, 82, 82, 0.12)"},
    {"--mantine-color-red-light-color": "var(--mantine-color-red-6)"},
    {"--mantine-color-red-outline": "var(--mantine-color-red-6)"},
    {"--mantine-color-red-outline-hover": "rgba(250, 82, 82, 0.05)"},
    {"--mantine-color-pink-text": "var(--mantine-color-pink-filled)"},
    {"--mantine-color-pink-filled": "var(--mantine-color-pink-6)"},
    {"--mantine-color-pink-filled-hover": "var(--mantine-color-pink-7)"},
    {"--mantine-color-pink-light": "rgba(230, 73, 128, 0.1)"},
    {"--mantine-color-pink-light-hover": "rgba(230, 73, 128, 0.12)"},
    {"--mantine-color-pink-light-color": "var(--mantine-color-pink-6)"},
    {"--mantine-color-pink-outline": "var(--mantine-color-pink-6)"},
    {"--mantine-color-pink-outline-hover": "rgba(230, 73, 128, 0.05)"},
    {"--mantine-color-grape-text": "var(--mantine-color-grape-filled)"},
    {"--mantine-color-grape-filled": "var(--mantine-color-grape-6)"},
    {"--mantine-color-grape-filled-hover": "var(--mantine-color-grape-7)"},
    {"--mantine-color-grape-light": "rgba(190, 75, 219, 0.1)"},
    {"--mantine-color-grape-light-hover": "rgba(190, 75, 219, 0.12)"},
    {"--mantine-color-grape-light-color": "var(--mantine-color-grape-6)"},
    {"--mantine-color-grape-outline": "var(--mantine-color-grape-6)"},
    {"--mantine-color-grape-outline-hover": "rgba(190, 75, 219, 0.05)"},
    {"--mantine-color-violet-text": "var(--mantine-color-violet-filled)"},
    {"--mantine-color-violet-filled": "var(--mantine-color-violet-6)"},
    {"--mantine-color-violet-filled-hover": "var(--mantine-color-violet-7)"},
    {"--mantine-color-violet-light": "rgba(121, 80, 242, 0.1)"},
    {"--mantine-color-violet-light-hover": "rgba(121, 80, 242, 0.12)"},
    {"--mantine-color-violet-light-color": "var(--mantine-color-violet-6)"},
    {"--mantine-color-violet-outline": "var(--mantine-color-violet-6)"},
    {"--mantine-color-violet-outline-hover": "rgba(121, 80, 242, 0.05)"},
    {"--mantine-color-indigo-text": "var(--mantine-color-indigo-filled)"},
    {"--mantine-color-indigo-filled": "var(--mantine-color-indigo-6)"},
    {"--mantine-color-indigo-filled-hover": "var(--mantine-color-indigo-7)"},
    {"--mantine-color-indigo-light": "rgba(76, 110, 245, 0.1)"},
    {"--mantine-color-indigo-light-hover": "rgba(76, 110, 245, 0.12)"},
    {"--mantine-color-indigo-light-color": "var(--mantine-color-indigo-6)"},
    {"--mantine-color-indigo-outline": "var(--mantine-color-indigo-6)"},
    {"--mantine-color-indigo-outline-hover": "rgba(76, 110, 245, 0.05)"},
    {"--mantine-color-blue-text": "var(--mantine-color-blue-filled)"},
    {"--mantine-color-blue-filled": "var(--mantine-color-blue-6)"},
    {"--mantine-color-blue-filled-hover": "var(--mantine-color-blue-7)"},
    {"--mantine-color-blue-light": "rgba(34, 139, 230, 0.1)"},
    {"--mantine-color-blue-light-hover": "rgba(34, 139, 230, 0.12)"},
    {"--mantine-color-blue-light-color": "var(--mantine-color-blue-6)"},
    {"--mantine-color-blue-outline": "var(--mantine-color-blue-6)"},
    {"--mantine-color-blue-outline-hover": "rgba(34, 139, 230, 0.05)"},
    {"--mantine-color-cyan-text": "var(--mantine-color-cyan-filled)"},
    {"--mantine-color-cyan-filled": "var(--mantine-color-cyan-6)"},
    {"--mantine-color-cyan-filled-hover": "var(--mantine-color-cyan-7)"},
    {"--mantine-color-cyan-light": "rgba(21, 170, 191, 0.1)"},
    {"--mantine-color-cyan-light-hover": "rgba(21, 170, 191, 0.12)"},
    {"--mantine-color-cyan-light-color": "var(--mantine-color-cyan-6)"},
    {"--mantine-color-cyan-outline": "var(--mantine-color-cyan-6)"},
    {"--mantine-color-cyan-outline-hover": "rgba(21, 170, 191, 0.05)"},
    {"--mantine-color-teal-text": "var(--mantine-color-teal-filled)"},
    {"--mantine-color-teal-filled": "var(--mantine-color-teal-6)"},
    {"--mantine-color-teal-filled-hover": "var(--mantine-color-teal-7)"},
    {"--mantine-color-teal-light": "rgba(18, 184, 134, 0.1)"},
    {"--mantine-color-teal-light-hover": "rgba(18, 184, 134, 0.12)"},
    {"--mantine-color-teal-light-color": "var(--mantine-color-teal-6)"},
    {"--mantine-color-teal-outline": "var(--mantine-color-teal-6)"},
    {"--mantine-color-teal-outline-hover": "rgba(18, 184, 134, 0.05)"},
    {"--mantine-color-green-text": "var(--mantine-color-green-filled)"},
    {"--mantine-color-green-filled": "var(--mantine-color-green-6)"},
    {"--mantine-color-green-filled-hover": "var(--mantine-color-green-7)"},
    {"--mantine-color-green-light": "rgba(64, 192, 87, 0.1)"},
    {"--mantine-color-green-light-hover": "rgba(64, 192, 87, 0.12)"},
    {"--mantine-color-green-light-color": "var(--mantine-color-green-6)"},
    {"--mantine-color-green-outline": "var(--mantine-color-green-6)"},
    {"--mantine-color-green-outline-hover": "rgba(64, 192, 87, 0.05)"},
    {"--mantine-color-lime-text": "var(--mantine-color-lime-filled)"},
    {"--mantine-color-lime-filled": "var(--mantine-color-lime-6)"},
    {"--mantine-color-lime-filled-hover": "var(--mantine-color-lime-7)"},
    {"--mantine-color-lime-light": "rgba(130, 201, 30, 0.1)"},
    {"--mantine-color-lime-light-hover": "rgba(130, 201, 30, 0.12)"},
    {"--mantine-color-lime-light-color": "var(--mantine-color-lime-6)"},
    {"--mantine-color-lime-outline": "var(--mantine-color-lime-6)"},
    {"--mantine-color-lime-outline-hover": "rgba(130, 201, 30, 0.05)"},
    {"--mantine-color-yellow-text": "var(--mantine-color-yellow-filled)"},
    {"--mantine-color-yellow-filled": "var(--mantine-color-yellow-6)"},
    {"--mantine-color-yellow-filled-hover": "var(--mantine-color-yellow-7)"},
    {"--mantine-color-yellow-light": "rgba(250, 176, 5, 0.1)"},
    {"--mantine-color-yellow-light-hover": "rgba(250, 176, 5, 0.12)"},
    {"--mantine-color-yellow-light-color": "var(--mantine-color-yellow-6)"},
    {"--mantine-color-yellow-outline": "var(--mantine-color-yellow-6)"},
    {"--mantine-color-yellow-outline-hover": "rgba(250, 176, 5, 0.05)"},
    {"--mantine-color-orange-text": "var(--mantine-color-orange-filled)"},
    {"--mantine-color-orange-filled": "var(--mantine-color-orange-6)"},
    {"--mantine-color-orange-filled-hover": "var(--mantine-color-orange-7)"},
    {"--mantine-color-orange-light": "rgba(253, 126, 20, 0.1)"},
    {"--mantine-color-orange-light-hover": "rgba(253, 126, 20, 0.12)"},
    {"--mantine-color-orange-light-color": "var(--mantine-color-orange-6)"},
    {"--mantine-color-orange-outline": "var(--mantine-color-orange-6)"},
    {"--mantine-color-orange-outline-hover": "rgba(253, 126, 20, 0.05)"}
]

def make_rows(data):
    rows = [
        dmc.Grid([
            dmc.GridCol(dmc.Text(key), span=5),
            dmc.GridCol(dmc.Text(value), span=5),
            dmc.GridCol(dmc.Box(h=24, w=24, bg=value), span=2),
            dmc.GridCol(dmc.Divider(), span=12)
        ])
        for item in data
        for key, value in item.items()
    ]
    return rows


component =  dmc.Box(
    make_rows(light_color_scheme)
)


